name: Raw Github Downloader
description: Download files from Github
author: Acme Software LLC

branding:
  icon: download-cloud
  color: blue

inputs:
  includes:
    description: Files to include
    required: true
  repo:
    description: Github repository
    required: true
  ref:
    description: Github branch / reference
    default: main
  git-pat:
    description: Github PAT
  output-directory:
    description: Output directory
    default: .
  
runs:
  using: node24
  main: dist/index.js