name: Github Downloader
description: Download files from Github
author: Acme Software LLC

branding:
  icon: download-cloud
  color: blue

inputs:
  mappings:
    description: File mappings in JSON format
    required: true
  owner:
    description: Github repository owner
    required: true
  repo:
    description: Github repository name
    required: true
  ref:
    description: Github branch / reference
    default: main
  token:
    description: The repository PAT or GITHUB_TOKEN.
    required: true
  output-directory:
    description: Output directory
    default: .
  
runs:
  using: node24
  main: dist/index.js
